// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX5lm0h4u-0vJm_hQTVHvefjTNSkYpU9c',
    appId: '1:154525884409:web:eaf0b203c1fdb351a96728',
    messagingSenderId: '154525884409',
    projectId: 'cpdhomeassignment2526',
    authDomain: 'cpdhomeassignment2526.firebaseapp.com',
    storageBucket: 'cpdhomeassignment2526.firebasestorage.app',
    measurementId: 'G-Y6T30NY36B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzUyFcnENladZHiaTDSQUDw_ct3faKshs',
    appId: '1:154525884409:android:fabd0ba26428756ba96728',
    messagingSenderId: '154525884409',
    projectId: 'cpdhomeassignment2526',
    storageBucket: 'cpdhomeassignment2526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuSd-Mj1gqEORVPGheyrIcNxFxm6TbJk',
    appId: '1:154525884409:ios:243a4fd0011086b7a96728',
    messagingSenderId: '154525884409',
    projectId: 'cpdhomeassignment2526',
    storageBucket: 'cpdhomeassignment2526.firebasestorage.app',
    iosBundleId: 'com.example.mfswd62bCpd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZuSd-Mj1gqEORVPGheyrIcNxFxm6TbJk',
    appId: '1:154525884409:ios:243a4fd0011086b7a96728',
    messagingSenderId: '154525884409',
    projectId: 'cpdhomeassignment2526',
    storageBucket: 'cpdhomeassignment2526.firebasestorage.app',
    iosBundleId: 'com.example.mfswd62bCpd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX5lm0h4u-0vJm_hQTVHvefjTNSkYpU9c',
    appId: '1:154525884409:web:917f63b7f47e7625a96728',
    messagingSenderId: '154525884409',
    projectId: 'cpdhomeassignment2526',
    authDomain: 'cpdhomeassignment2526.firebaseapp.com',
    storageBucket: 'cpdhomeassignment2526.firebasestorage.app',
    measurementId: 'G-FCC1VLT7KV',
  );
}
