// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/asset.dart';
import 'models/asset_location.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8014627527191618653),
    name: 'Asset',
    lastPropertyId: const obx_int.IdUid(7, 5040272887353922637),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4322038505590940249),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3920705184743418150),
        name: 'assetLocationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 2234400058355222184),
        relationField: 'assetLocation',
        relationTarget: 'AssetLocation',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4367173278347829527),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9125207870117589444),
        name: 'serialNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9007594376295194735),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7050165405049558587),
        name: 'dateCreatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5040272887353922637),
        name: 'assetTypeIndex',
        type: 2,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5276684097298549980),
    name: 'AssetLocation',
    lastPropertyId: const obx_int.IdUid(3, 3606377854039021069),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3711922629048250033),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1714804950993016834),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3606377854039021069),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5276684097298549980),
    lastIndexId: const obx_int.IdUid(1, 2234400058355222184),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Asset: obx_int.EntityDefinition<Asset>(
      model: _entities[0],
      toOneRelations: (Asset object) => [object.assetLocation],
      toManyRelations: (Asset object) => {},
      getId: (Asset object) => object.id,
      setId: (Asset object, int id) {
        object.id = id;
      },
      objectToFB: (Asset object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final serialNumberOffset = fbb.writeString(object.serialNumber);
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.assetLocation.targetId);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, serialNumberOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addInt64(5, object.dateCreatedAt.millisecondsSinceEpoch);
        fbb.addInt8(6, object.assetTypeIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final serialNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final assetTypeIndexParam = const fb.Int8Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object =
            Asset(
                name: nameParam,
                serialNumber: serialNumberParam,
                description: descriptionParam,
                assetTypeIndex: assetTypeIndexParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..dateCreatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
              );
        object.assetLocation.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.assetLocation.attach(store);
        return object;
      },
    ),
    AssetLocation: obx_int.EntityDefinition<AssetLocation>(
      model: _entities[1],
      toOneRelations: (AssetLocation object) => [],
      toManyRelations: (AssetLocation object) => {},
      getId: (AssetLocation object) => object.id,
      setId: (AssetLocation object, int id) {
        object.id = id;
      },
      objectToFB: (AssetLocation object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.latitude);
        fbb.addFloat64(2, object.longitude);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = AssetLocation(
          latitude: latitudeParam,
          longitude: longitudeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Asset] entity fields to define ObjectBox queries.
class Asset_ {
  /// See [Asset.id].
  static final id = obx.QueryIntegerProperty<Asset>(_entities[0].properties[0]);

  /// See [Asset.assetLocation].
  static final assetLocation = obx.QueryRelationToOne<Asset, AssetLocation>(
    _entities[0].properties[1],
  );

  /// See [Asset.name].
  static final name = obx.QueryStringProperty<Asset>(
    _entities[0].properties[2],
  );

  /// See [Asset.serialNumber].
  static final serialNumber = obx.QueryStringProperty<Asset>(
    _entities[0].properties[3],
  );

  /// See [Asset.description].
  static final description = obx.QueryStringProperty<Asset>(
    _entities[0].properties[4],
  );

  /// See [Asset.dateCreatedAt].
  static final dateCreatedAt = obx.QueryDateProperty<Asset>(
    _entities[0].properties[5],
  );

  /// See [Asset.assetTypeIndex].
  static final assetTypeIndex = obx.QueryIntegerProperty<Asset>(
    _entities[0].properties[6],
  );
}

/// [AssetLocation] entity fields to define ObjectBox queries.
class AssetLocation_ {
  /// See [AssetLocation.id].
  static final id = obx.QueryIntegerProperty<AssetLocation>(
    _entities[1].properties[0],
  );

  /// See [AssetLocation.latitude].
  static final latitude = obx.QueryDoubleProperty<AssetLocation>(
    _entities[1].properties[1],
  );

  /// See [AssetLocation.longitude].
  static final longitude = obx.QueryDoubleProperty<AssetLocation>(
    _entities[1].properties[2],
  );
}
